version: "3.3"

services:
  dht-gateway:
    container_name: dht-gateway
    build:
      context: ./dht-gateway
      dockerfile: Dockerfile
    network_mode: host
    restart: always

  dht-bootstrap-node_1:
    container_name: dht-bootstrap-node_1
    build:
      context: ./bittorrent-dht-node
      dockerfile: Dockerfile
    restart: always
    environment:
      - BOOTSTRAP_NODES=dht-bootstrap-node_2:6902,dht-bootstrap-node_3:6903
      - NODE_LISTEN_PORT=6901
      - API_LISTEN_PORT=3001
    ports:
      - 6901:6901/udp
      - 3001:3001
  dht-bootstrap-node_2:
    container_name: dht-bootstrap-node_2
    build:
      context: ./bittorrent-dht-node
      dockerfile: Dockerfile
    restart: always
    environment:
      - BOOTSTRAP_NODES=dht-bootstrap-node_1:6901,dht-bootstrap-node_3:6903
      - NODE_LISTEN_PORT=6902
      - API_LISTEN_PORT=3002
    ports:
      - 6902:6902/udp
      - 3002:3002
  dht-bootstrap-node_3:
    container_name: dht-bootstrap-node_3
    build:
      context: ./bittorrent-dht-node
      dockerfile: Dockerfile
    restart: always
    environment:
      - BOOTSTRAP_NODES=dht-bootstrap-node_1:6901,dht-bootstrap-node_2:6902
      - NODE_LISTEN_PORT=6903
      - API_LISTEN_PORT=3003
    ports:
      - 6903:6903/udp
      - 3003:3003

  keyserver-mongodb:
    container_name: keyserver-mongodb
    image: mongo:4.2.3-bionic
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null

  keyserver:
    container_name: keyserver
    build:
      context: ./keyserver
      dockerfile: Dockerfile
    env_file: ./keyserver/.env
    ports:
      - 8888:8888
    depends_on:
      - keyserver-mongodb
