version: "3.3"

services:
  dht-bootstrap-node:
    container_name: dht-bootstrap-node
    image: gus33/bittorrent-dht-node:stable
    network_mode: host

  keyserver-mongodb:
    container_name: keyserver-mongodb
    image: mongo:4.2.3-bionic
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null

  keyserver:
    container_name: keyserver
    image: gus33/keyserver:stable
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - keyserver-mongodb
