version: "3.3"

services:
  isys-mongodb:
    container_name: isys-mongodb
    image: mongo:4.2.3-bionic
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod

  isys-api:
    container_name: isys-api
    image: registry.dotwave.io/isys-api:stable
    restart: always
    ports:
      - 8008:8080
    depends_on:
      - isys-mongodb
